// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvfoxtvqqdkrjumcvntl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2Zm94dHZxcWRrcmp1bWN2bnRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NzAwMDksImV4cCI6MjA3NDU0NjAwOX0.ILivIhlK8l5wPbZRr47H4qkuLFg3BPePmZEeTJ_SiQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});