// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import {
  logLogin,
  logLogout,
  logSignUp,
  logProfileEdit,
  logAddToCart,
  logNewOrder,
} from "@/lib/utils";

// ✅ Get keys from environment
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// ✅ Create Supabase client
export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);

// ✅ Flag to ignore first automatic SIGNED_IN event (page refresh)
let hasEmittedInitialSession = false;

// ✅ Check existing session on load (so we know if user was already logged in)
(async () => {
  const { data } = await supabase.auth.getSession();
  if (data.session) {
    hasEmittedInitialSession = true;
  }
})();

// ✅ Listen for auth state changes (fixed refresh issue)
supabase.auth.onAuthStateChange(async (event, session) => {
  const user = session?.user;

  if (event === "SIGNED_IN" && user) {
    // ✅ Ignore the first auto-emitted SIGNED_IN (page refresh)
    if (!hasEmittedInitialSession) {
      hasEmittedInitialSession = true;
      return;
    }

    // ✅ Detect signup vs normal login
    const created = new Date(user.created_at).getTime();
    const lastLogin = new Date(user.last_sign_in_at ?? "").getTime();

    
    if (Math.abs(created - lastLogin) < 5000) {
      await logSignUp(user);
    } else {
      await logLogin(user, session);
    }
  }

  if (event === "SIGNED_OUT" && user) {
    await logLogout(user);
  }
});

// ✅ Example helper: update profile
export async function updateProfile(user: any, updates: Record<string, any>) {
  const { data, error } = await supabase
    .from("profiles")
    .update(updates)
    .eq("id", user.id);

  if (!error) {
    await logProfileEdit(user, updates);
  } else {
    console.error("❌ Profile update error:", error);
  }

  return { data, error };
}

// ✅ Example helper: add to cart
export async function addToCart(user: any, product: any, cartStore: any) {
  cartStore.add(product);
  await logAddToCart(user, product);
}

// ✅ Example helper: create order
export async function createOrder(order: any) {
  const { data, error } = await supabase.from("orders").insert(order);

  if (!error) {
    await logNewOrder(order);
  } else {
    console.error("❌ Order creation error:", error);
  }

  return { data, error };
}
